# Generated by Django 4.2.6 on 2023-10-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=300)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_deadline', models.DateTimeField()),
            ],
        ),
    ]
